name: 'uv-install-package'
description: |
  Install Python packages with uv, auto-resolving compatible versions for your target
  Python environment via PyPI.

author: "Thibaut Durand"

branding:
  icon: 'box'
  color: 'purple'

inputs:
  package-name:
    description: 'The package name (e.g., numpy, requests, django)'
    required: true
  package-version:
    description: 'The target package version (e.g., "1.2.3", "2.0.0")'
    required: true
  python-version:
    description: 'The Python version to check compatibility against (e.g., "3.10", "3.11", "3.12")'
    required: true
  uv-args:
    description: 'Additional arguments to pass to uv (e.g., "--index-url https://custom.pypi.org/simple")'
    required: false
    default: ''

outputs:
  closest-valid-version:
    description: 'The closest valid package version that matches your constraints and is compatible with the specified Python version'
    value: ${{ steps.find-version.outputs.closest-valid-version }}
  installed-successfully:
    description: 'Boolean indicating whether the package was installed successfully'
    value: ${{ steps.install-package.outcome == 'success' }}

runs:
  using: "composite"
  steps:
    # ============================================================================
    # Step 1: Verify uv package manager is available
    # ============================================================================
    # Check that uv is installed and available on the runner. This action
    # requires uv to be pre-installed (e.g., via astral-sh/setup-uv action).
    # Displays the installation path and version for debugging purposes.
    - name: Verify uv is installed
      shell: bash
      run: |
        set -euo pipefail

        echo "🔍 Checking for uv installation..."

        if ! command -v uv &> /dev/null; then
          echo "::error::❌ uv is not installed or not in PATH. Please install uv before using this action (e.g., use astral-sh/setup-uv)"
          exit 1
        fi

        # Display uv location and version information
        echo "✅ uv is installed"
        echo "📍 Location: $(which uv)"
        echo "🏷️  Version: $(uv --version)"

    # ============================================================================
    # Step 2: Validate and normalize Python version
    # ============================================================================
    # Validates that the Python version is in major.minor format (e.g., "3.10").
    # If a patch version is provided (e.g., "3.10.1"), it will be normalized
    # to just major.minor (e.g., "3.10").
    - name: Validate Python version
      id: validate-python-version
      shell: bash
      run: |
        set -euo pipefail

        PYTHON_VERSION="${{ inputs.python-version }}"
        echo "🔍 Validating Python version: $PYTHON_VERSION"

        # Call the validation script
        SCRIPT_PATH="${{ github.action_path }}/scripts/validate_python_version.sh"
        if ! NORMALIZED_VERSION=$("$SCRIPT_PATH" "$PYTHON_VERSION" 2>&1); then
          echo "::error::❌ Invalid Python version format: '$PYTHON_VERSION'. Expected format: 'X.Y' or 'X.Y.Z' (e.g., '3.10' or '3.10.1')"
          exit 1
        fi

        echo "✅ Python version validated: $NORMALIZED_VERSION"

        # Show warning if patch version was provided and normalized
        TRIMMED_INPUT=$(echo "$PYTHON_VERSION" | xargs)
        if [ "$TRIMMED_INPUT" != "$NORMALIZED_VERSION" ]; then
          echo "::warning::Python version '$PYTHON_VERSION' normalized to '$NORMALIZED_VERSION' (patch version ignored)"
        fi

        # Export the normalized version for use in subsequent steps
        echo "normalized-python-version=$NORMALIZED_VERSION" >> "$GITHUB_OUTPUT"

    # ============================================================================
    # Step 3: Install feu package for version resolution
    # ============================================================================
    # The 'feu' package provides utilities to find compatible package versions
    # based on Python version constraints. We install it with the [cli] extra
    # to get command-line tools.
    - name: Install dependencies
      shell: bash
      run: |
        # Exit immediately if any command fails
        set -euo pipefail
        echo "📦 Installing feu package..."
        uv pip install "feu[cli]>=0.6.2,<0.7.0"
        echo "✅ Dependencies installed"

    # ============================================================================
    # Step 4: Find the closest valid package version
    # ============================================================================
    # Query PyPI to find the closest available version that matches:
    # - The requested package version (exact or range)
    # - Compatibility with the specified Python version
    # This prevents installation failures from incompatible versions.
    - name: Find closest valid version
      id: find-version
      shell: bash
      run: |
        set -euo pipefail

        NORMALIZED_PYTHON_VERSION="${{ steps.validate-python-version.outputs.normalized-python-version }}"

        echo "🔎 Searching for closest valid version..."
        echo "  📦 Package: ${{ inputs.package-name }}"
        echo "  🎯 Target version: ${{ inputs.package-version }}"
        echo "  🐍 Python version: $NORMALIZED_PYTHON_VERSION"

        # Run feu to resolve the closest compatible version
        if ! VERSION=$(python -m feu find-closest-version \
          --pkg-name="${{ inputs.package-name }}" \
          --pkg-version="${{ inputs.package-version }}" \
          --python-version="$NORMALIZED_PYTHON_VERSION" 2>&1); then
          echo "::error::❌ Failed to query PyPI for package '${{ inputs.package-name }}'. Check network connectivity and package name."
          exit 1
        fi

        # Validate that we got a version back
        if [ -z "$VERSION" ]; then
          echo "::error::❌ No compatible version found for package '${{ inputs.package-name }}' version '${{ inputs.package-version }}' with Python $NORMALIZED_PYTHON_VERSION"
          exit 1
        fi

        echo "✅ Found closest valid version: $VERSION"
        # Export the version for use in subsequent steps
        echo "closest-valid-version=$VERSION" >> "$GITHUB_OUTPUT"

    # ============================================================================
    # Step 5: Install the resolved package version
    # ============================================================================
    # Use feu's installer wrapper to install the package with uv.
    # This ensures consistent installation behavior and proper handling of
    # any additional uv arguments passed by the user.
    - name: Install package
      id: install-package
      shell: bash
      run: |
        set -euo pipefail

        # Get the version we resolved in the previous step
        CLOSEST_VERSION="${{ steps.find-version.outputs.closest-valid-version }}"

        echo "📥 Installing package..."
        echo "  📦 Package: ${{ inputs.package-name }}"
        echo "  🏷️  Version: $CLOSEST_VERSION"

        # Install the package using feu's installer wrapper
        python -m feu install \
          --installer-name=uv \
          --installer-args="${{ inputs.uv-args }}" \
          --pkg-name="${{ inputs.package-name }}" \
          --pkg-version="$CLOSEST_VERSION"

        echo "::notice::✅ Successfully installed ${{ inputs.package-name }}==$CLOSEST_VERSION"
